### ISSUE TITLE
No any option available in dashboard.

### ISSUE THREAD

**Issue by skyshinein31** [Paytm-Payments/Paytm_Gratification_Kit#10]
I tried all your instruction files and tried to follow your instructions to create sub-wallet and all. But there are no any similar options in dashboard are available and also not able to find any documentations on official website of paytm. Your given link "wallet.paytm.in/wallet-merchant/" also broken and your developer website "http://paywithpaytm.com/developer/" is still not working.

Please any help to get "PAYTM_MERCHANT_GUID" and "PAYTM_SALES_WALLET_GUID"....?

**Comment by kanwal08** [comment]
I'm also facing the same problem. Any solution?

**Comment by skyshinein31** [comment]
Yes! You can contact Paytm Support, They'll do it for you. This is another secure process of verification.
